"""add question answers table

Revision ID: e5b0a5d4372d
Revises: 23cf478b83cd
Create Date: 2025-09-23 14:53:28.115427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e5b0a5d4372d"
down_revision: Union[str, Sequence[str], None] = "23cf478b83cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type if it doesn't exist
    connection = op.get_bind()

    # Check if enum exists
    result = connection.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'answerstatus'")).fetchone()

    if not result:
        # Create the enum type
        op.execute("CREATE TYPE answerstatus AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRY')")

    # Create the table without the enum column first
    op.create_table(
        "question_messages_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.String(), nullable=False),
        sa.Column("processing_started_at", sa.DateTime(), nullable=True),
        sa.Column("processing_completed_at", sa.DateTime(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("answer_confidence", sa.Float(), nullable=True),
        sa.Column("answer_quality_score", sa.Integer(), nullable=True),
        sa.Column("llm_raw_response", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["comment_id"], ["comments_classification.comment_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Add the enum column separately
    op.add_column(
        "question_messages_answers",
        sa.Column(
            "processing_status",
            postgresql.ENUM("PENDING", "PROCESSING", "COMPLETED", "FAILED", "RETRY", name="answerstatus"),
            nullable=False,
            server_default="PENDING",
        ),
    )

    op.create_index(
        op.f("ix_question_messages_answers_comment_id"), "question_messages_answers", ["comment_id"], unique=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_question_messages_answers_comment_id"), table_name="question_messages_answers")
    op.drop_table("question_messages_answers")
    # ### end Alembic commands ###
