"""add_reply_id_field_to_prevent_infinite_loops

Revision ID: 29a5d71fb868
Revises: c2ae07ed834e
Create Date: 2025-09-23 22:26:38.149823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29a5d71fb868"
down_revision: Union[str, Sequence[str], None] = "c2ae07ed834e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question_messages_answers", sa.Column("reply_id", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_messages_answers", "reply_id")
    # ### end Alembic commands ###
