"""add_media_context_column

Revision ID: b92884ea1bf0
Revises: add_token_usage_fields
Create Date: 2025-10-04 19:06:01.094506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b92884ea1bf0'
down_revision: Union[str, Sequence[str], None] = 'add_token_usage_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique document identifier'),
    sa.Column('client_id', sa.String(length=100), nullable=False, comment='Instagram business account ID'),
    sa.Column('client_name', sa.String(length=200), nullable=True, comment='Business name'),
    sa.Column('document_name', sa.String(length=500), nullable=False, comment='Original document filename'),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='Document type: pdf, excel, csv, word, txt'),
    sa.Column('description', sa.Text(), nullable=True, comment='Human-readable document description'),
    sa.Column('s3_bucket', sa.String(length=200), nullable=False, comment='S3 bucket name'),
    sa.Column('s3_key', sa.String(length=500), nullable=False, comment='S3 object key/path'),
    sa.Column('s3_url', sa.Text(), nullable=False, comment='Full S3 URL or presigned URL'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True, comment='Original file size in bytes'),
    sa.Column('markdown_content', sa.Text(), nullable=True, comment='Document content extracted and converted to markdown'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash of content for deduplication'),
    sa.Column('processing_status', sa.String(length=50), nullable=False, comment='Processing status: pending, processing, completed, failed'),
    sa.Column('processing_error', sa.Text(), nullable=True, comment='Error message if processing failed'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='When document processing completed'),
    sa.Column('embedding_status', sa.String(length=50), nullable=False, comment='Vector embedding status for future semantic search'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Categorization tags and metadata'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='When record was last updated'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='User/system who uploaded the document'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client_document_unique', 'client_documents', ['client_id', 'content_hash'], unique=True, postgresql_where='content_hash IS NOT NULL')
    op.create_index('idx_client_documents_client_id', 'client_documents', ['client_id'], unique=False)
    op.create_index('idx_client_documents_status', 'client_documents', ['processing_status'], unique=False)
    op.create_index('idx_client_documents_type', 'client_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_client_documents_client_id'), 'client_documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_documents_content_hash'), 'client_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_client_documents_document_type'), 'client_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_client_documents_processing_status'), 'client_documents', ['processing_status'], unique=False)
    op.add_column('media', sa.Column('media_context', sa.String(), nullable=True, comment='AI-generated detailed description and context of the media image'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'media_context')
    op.drop_index(op.f('ix_client_documents_processing_status'), table_name='client_documents')
    op.drop_index(op.f('ix_client_documents_document_type'), table_name='client_documents')
    op.drop_index(op.f('ix_client_documents_content_hash'), table_name='client_documents')
    op.drop_index(op.f('ix_client_documents_client_id'), table_name='client_documents')
    op.drop_index('idx_client_documents_type', table_name='client_documents')
    op.drop_index('idx_client_documents_status', table_name='client_documents')
    op.drop_index('idx_client_documents_client_id', table_name='client_documents')
    op.drop_index('idx_client_document_unique', table_name='client_documents', postgresql_where='content_hash IS NOT NULL')
    op.drop_table('client_documents')
    # ### end Alembic commands ###
