"""add_media_table

Revision ID: ffa28b3b3306
Revises: e2a96501d9c0
Create Date: 2025-09-28 12:33:20.052274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ffa28b3b3306"
down_revision: Union[str, Sequence[str], None] = "e2a96501d9c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.String(length=100), nullable=False, comment="Instagram media ID"),
        sa.Column("permalink", sa.String(length=500), nullable=False, comment="Instagram post permalink URL"),
        sa.Column("caption", sa.String(length=2000), nullable=True, comment="Post caption text"),
        sa.Column("media_url", sa.String(length=500), nullable=True, comment="URL to the media file"),
        sa.Column(
            "media_type", sa.String(length=50), nullable=True, comment="Type of media (IMAGE, VIDEO, CAROUSEL_ALBUM)"
        ),
        sa.Column("comments_count", sa.Integer(), nullable=True, comment="Number of comments on the post"),
        sa.Column("like_count", sa.Integer(), nullable=True, comment="Number of likes on the post"),
        sa.Column("shortcode", sa.String(length=100), nullable=True, comment="Instagram shortcode"),
        sa.Column("timestamp", sa.DateTime(), nullable=True, comment="When the media was posted on Instagram"),
        sa.Column("is_comment_enabled", sa.Boolean(), nullable=True, comment="Whether comments are enabled"),
        sa.Column("username", sa.String(length=100), nullable=True, comment="Username of the media owner"),
        sa.Column("owner", sa.String(length=100), nullable=True, comment="Owner account ID"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="When this record was created"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="When this record was last updated"),
        sa.Column(
            "raw_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Raw Instagram API response data",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "instagram_comments",
        "conversation_id",
        existing_type=sa.VARCHAR(length=100),
        comment="Conversation ID for session management - first_question_comment_{id} format",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "instagram_comments",
        "conversation_id",
        existing_type=sa.VARCHAR(length=100),
        comment=None,
        existing_comment="Conversation ID for session management - first_question_comment_{id} format",
        existing_nullable=True,
    )
    op.drop_table("media")
    # ### end Alembic commands ###
