"""remove_caption_length_restriction

Revision ID: 9e9143163be5
Revises: ffa28b3b3306
Create Date: 2025-09-28 12:35:15.607757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e9143163be5"
down_revision: Union[str, Sequence[str], None] = "ffa28b3b3306"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove length restriction from caption field
    op.alter_column(
        "media",
        "caption",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(),
        existing_nullable=True,
        existing_comment="Post caption text",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Restore length restriction to caption field
    op.alter_column(
        "media",
        "caption",
        existing_type=sa.String(),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
        existing_comment="Post caption text",
    )
    # ### end Alembic commands ###
