"""add_instagram_reply_tracking_fields

Revision ID: c2ae07ed834e
Revises: e5b0a5d4372d
Create Date: 2025-09-23 19:40:19.928408

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2ae07ed834e"
down_revision: Union[str, Sequence[str], None] = "e5b0a5d4372d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add reply_sent column with default value first
    op.add_column(
        "question_messages_answers", sa.Column("reply_sent", sa.Boolean(), nullable=False, server_default="false")
    )
    op.add_column("question_messages_answers", sa.Column("reply_sent_at", sa.DateTime(), nullable=True))
    op.add_column("question_messages_answers", sa.Column("reply_status", sa.String(length=50), nullable=True))
    op.add_column("question_messages_answers", sa.Column("reply_error", sa.Text(), nullable=True))
    op.add_column("question_messages_answers", sa.Column("reply_response", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question_messages_answers", "reply_response")
    op.drop_column("question_messages_answers", "reply_error")
    op.drop_column("question_messages_answers", "reply_status")
    op.drop_column("question_messages_answers", "reply_sent_at")
    op.drop_column("question_messages_answers", "reply_sent")
    # ### end Alembic commands ###
