"""add_conversation_id_to_question_answer

Revision ID: 746f3c4b287e
Revises: 7d7a6a6abc68
Create Date: 2025-09-27 22:33:36.936499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "746f3c4b287e"
down_revision: Union[str, Sequence[str], None] = "7d7a6a6abc68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question_messages_answers", sa.Column("conversation_id", sa.String(length=100), nullable=True))
    op.create_index(
        op.f("ix_question_messages_answers_conversation_id"),
        "question_messages_answers",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_question_messages_answers_conversation_id"), table_name="question_messages_answers")
    op.drop_column("question_messages_answers", "conversation_id")
    # ### end Alembic commands ###
