"""increase_classification_field_length

Revision ID: e8e210e581a0
Revises: 5fdaddf292ca
Create Date: 2025-09-27 17:05:20.914254

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8e210e581a0"
down_revision: Union[str, Sequence[str], None] = "5fdaddf292ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comments_classification",
        "classification",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("uq_question_answers_reply_id"), "question_messages_answers", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_question_answers_reply_id"),
        "question_messages_answers",
        ["reply_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "comments_classification",
        "classification",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
