"""add_foreign_key_constraint_media_id

Revision ID: 46e554b1b3e6
Revises: 9e9143163be5
Create Date: 2025-09-28 12:52:08.550838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46e554b1b3e6"
down_revision: Union[str, Sequence[str], None] = "9e9143163be5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "instagram_comments",
        "media_id",
        existing_type=sa.VARCHAR(),
        comment="Foreign key to media table",
        existing_nullable=False,
    )
    op.create_foreign_key(None, "instagram_comments", "media", ["media_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "instagram_comments", type_="foreignkey")
    op.alter_column(
        "instagram_comments",
        "media_id",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Foreign key to media table",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
