"""add_parent_id_to_comments

Revision ID: f0c8ff6d881d
Revises: 746f3c4b287e
Create Date: 2025-09-27 22:48:50.065142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0c8ff6d881d"
down_revision: Union[str, Sequence[str], None] = "746f3c4b287e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instagram_comments",
        sa.Column(
            "parent_id",
            sa.String(length=100),
            nullable=True,
            comment="ID of the parent comment if this is a reply, NULL if it's a top-level comment",
        ),
    )
    op.create_index(op.f("ix_instagram_comments_parent_id"), "instagram_comments", ["parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_instagram_comments_parent_id"), table_name="instagram_comments")
    op.drop_column("instagram_comments", "parent_id")
    # ### end Alembic commands ###
